module.exports=[46058,(a,b,c)=>{"use strict";function d(a){if("function"!=typeof WeakMap)return null;var b=new WeakMap,c=new WeakMap;return(d=function(a){return a?c:b})(a)}c._=function(a,b){if(!b&&a&&a.__esModule)return a;if(null===a||"object"!=typeof a&&"function"!=typeof a)return{default:a};var c=d(b);if(c&&c.has(a))return c.get(a);var e={__proto__:null},f=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var g in a)if("default"!==g&&Object.prototype.hasOwnProperty.call(a,g)){var h=f?Object.getOwnPropertyDescriptor(a,g):null;h&&(h.get||h.set)?Object.defineProperty(e,g,h):e[g]=a[g]}return e.default=a,c&&c.set(a,e),e}},39118,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0});var d={DEFAULT_SEGMENT_KEY:function(){return l},NOT_FOUND_SEGMENT_KEY:function(){return m},PAGE_SEGMENT_KEY:function(){return k},addSearchParamsIfPageSegment:function(){return i},computeSelectedLayoutSegment:function(){return j},getSegmentValue:function(){return f},getSelectedLayoutSegmentPath:function(){return function a(b,c,d=!0,e=[]){let g;if(d)g=b[1][c];else{let a=b[1];g=a.children??Object.values(a)[0]}if(!g)return e;let h=f(g[0]);return!h||h.startsWith(k)?e:(e.push(h),a(g,c,!1,e))}},isGroupSegment:function(){return g},isParallelRouteSegment:function(){return h}};for(var e in d)Object.defineProperty(c,e,{enumerable:!0,get:d[e]});function f(a){return Array.isArray(a)?a[1]:a}function g(a){return"("===a[0]&&a.endsWith(")")}function h(a){return a.startsWith("@")&&"@children"!==a}function i(a,b){if(a.includes(k)){let a=JSON.stringify(b);return"{}"!==a?k+"?"+a:k}return a}function j(a,b){if(!a||0===a.length)return null;let c="children"===b?a[0]:a[a.length-1];return c===l?null:c}let k="__PAGE__",l="__DEFAULT__",m="/_not-found"},88644,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"InvariantError",{enumerable:!0,get:function(){return d}});class d extends Error{constructor(a,b){super(`Invariant: ${a.endsWith(".")?a:a+"."} This is a bug in Next.js.`,b),this.name="InvariantError"}}},54427,(a,b,c)=>{"use strict";function d(){let a,b,c=new Promise((c,d)=>{a=c,b=d});return{resolve:a,reject:b,promise:c}}Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"createPromiseWithResolvers",{enumerable:!0,get:function(){return d}})},71897,a=>{"use strict";var b=a.i(78560);function c(a){var b;return{...a,offer:(b=a.offer)?Array.isArray(b)?b[0]??null:b:null}}function d(a){return Array.isArray(a)?a.map(c):[]}async function e(a){let c=a.trim().toLowerCase(),{data:d,error:e}=await b.supabase.from("therapists").select("id").ilike("email",c).maybeSingle();if(e)throw Error(`N\xe3o foi poss\xedvel localizar o terapeuta: ${e.message}`);if(!d)throw Error("Nenhum terapeuta foi encontrado para o e-mail desta conta.");return d.id}async function f(a){let{data:c,error:d}=await b.supabase.from("therapists").select("id").eq("profile_id",a).maybeSingle();if(d)throw Error(`N\xe3o foi poss\xedvel localizar o terapeuta: ${d.message}`);if(!c)throw Error("Nenhum terapeuta foi encontrado para esta conta.");return c.id}async function g(a){let{data:c,error:d}=await b.supabase.from("clients").select("id").eq("profile_id",a).maybeSingle();if(d)throw Error(`N\xe3o foi poss\xedvel localizar o cliente: ${d.message}`);if(!c)throw Error("Nenhum cliente foi encontrado para esta conta.");return c.id}async function h(a){let{data:c,error:e}=await b.supabase.from("appointments").select(`
        id,
        therapist_id,
        client_id,
        offer_id,
        client_name,
        client_email,
        client_phone,
        preferred_date,
        preferred_time,
        proposed_date,
        proposed_time,
        confirmed_date,
        confirmed_time,
        modality,
        message,
        therapist_response,
        price,
        status,
        appointment_date,
        created_at,
        updated_at,
        offer:offers (
          id,
          title,
          offer_type,
          offer_price,
          duration,
          service_type
        )
      `).eq("therapist_id",a).order("updated_at",{ascending:!1});if(e)throw Error(`N\xe3o foi poss\xedvel carregar os agendamentos: ${e.message}`);return d(c)}async function i(a){let{data:c,error:e}=await b.supabase.from("appointments").select(`
        id,
        therapist_id,
        client_id,
        offer_id,
        client_name,
        client_email,
        client_phone,
        preferred_date,
        preferred_time,
        proposed_date,
        proposed_time,
        confirmed_date,
        confirmed_time,
        modality,
        message,
        therapist_response,
        price,
        status,
        appointment_date,
        created_at,
        updated_at,
        offer:offers (
          id,
          title,
          offer_type,
          offer_price,
          duration,
          service_type
        )
      `).eq("client_id",a).order("updated_at",{ascending:!1});if(e)throw Error(`N\xe3o foi poss\xedvel carregar os atendimentos do cliente: ${e.message}`);return d(c)}async function j(a,c,d){let{error:e}=await b.supabase.from("appointments").update({status:"awaiting_payment",confirmed_date:c,confirmed_time:d,updated_at:new Date().toISOString()}).eq("id",a);if(e)throw Error(`N\xe3o foi poss\xedvel aceitar o agendamento: ${e.message}`)}async function k(a,c,d){let{error:e}=await b.supabase.from("appointments").update({status:"new_time_proposed",proposed_date:c,proposed_time:d,updated_at:new Date().toISOString()}).eq("id",a);if(e)throw Error(`N\xe3o foi poss\xedvel propor um novo hor\xe1rio: ${e.message}`)}async function l(a){let{error:c}=await b.supabase.from("appointments").update({status:"declined",updated_at:new Date().toISOString()}).eq("id",a);if(c)throw Error(`N\xe3o foi poss\xedvel recusar o agendamento: ${c.message}`)}a.s(["acceptAppointment",0,j,"declineAppointment",0,l,"getAppointmentsByClientId",0,i,"getAppointmentsByTherapistId",0,h,"getClientIdByProfileId",0,g,"getTherapistIdByEmail",0,e,"getTherapistIdByProfileId",0,f,"proposeNewAppointmentTime",0,k])}];

//# sourceMappingURL=_0xlxsxc._.js.map