module.exports=[46058,(a,b,c)=>{"use strict";function d(a){if("function"!=typeof WeakMap)return null;var b=new WeakMap,c=new WeakMap;return(d=function(a){return a?c:b})(a)}c._=function(a,b){if(!b&&a&&a.__esModule)return a;if(null===a||"object"!=typeof a&&"function"!=typeof a)return{default:a};var c=d(b);if(c&&c.has(a))return c.get(a);var e={__proto__:null},f=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var g in a)if("default"!==g&&Object.prototype.hasOwnProperty.call(a,g)){var h=f?Object.getOwnPropertyDescriptor(a,g):null;h&&(h.get||h.set)?Object.defineProperty(e,g,h):e[g]=a[g]}return e.default=a,c&&c.set(a,e),e}},39118,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0});var d={DEFAULT_SEGMENT_KEY:function(){return l},NOT_FOUND_SEGMENT_KEY:function(){return m},PAGE_SEGMENT_KEY:function(){return k},addSearchParamsIfPageSegment:function(){return i},computeSelectedLayoutSegment:function(){return j},getSegmentValue:function(){return f},getSelectedLayoutSegmentPath:function(){return function a(b,c,d=!0,e=[]){let g;if(d)g=b[1][c];else{let a=b[1];g=a.children??Object.values(a)[0]}if(!g)return e;let h=f(g[0]);return!h||h.startsWith(k)?e:(e.push(h),a(g,c,!1,e))}},isGroupSegment:function(){return g},isParallelRouteSegment:function(){return h}};for(var e in d)Object.defineProperty(c,e,{enumerable:!0,get:d[e]});function f(a){return Array.isArray(a)?a[1]:a}function g(a){return"("===a[0]&&a.endsWith(")")}function h(a){return a.startsWith("@")&&"@children"!==a}function i(a,b){if(a.includes(k)){let a=JSON.stringify(b);return"{}"!==a?k+"?"+a:k}return a}function j(a,b){if(!a||0===a.length)return null;let c="children"===b?a[0]:a[a.length-1];return c===l?null:c}let k="__PAGE__",l="__DEFAULT__",m="/_not-found"},88644,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"InvariantError",{enumerable:!0,get:function(){return d}});class d extends Error{constructor(a,b){super(`Invariant: ${a.endsWith(".")?a:a+"."} This is a bug in Next.js.`,b),this.name="InvariantError"}}},54427,(a,b,c)=>{"use strict";function d(){let a,b,c=new Promise((c,d)=>{a=c,b=d});return{resolve:a,reject:b,promise:c}}Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"createPromiseWithResolvers",{enumerable:!0,get:function(){return d}})},71897,a=>{"use strict";var b=a.i(78560);function c(a){var b;return{...a,offer:(b=a.offer)?Array.isArray(b)?b[0]??null:b:null}}function d(a){return Array.isArray(a)?a.map(c):[]}async function e(a){let c=a.trim().toLowerCase(),{data:d,error:e}=await b.supabase.from("therapists").select("id").ilike("email",c).maybeSingle();if(e)throw Error(`N\xe3o foi poss\xedvel localizar o terapeuta: ${e.message}`);if(!d)throw Error("Nenhum terapeuta foi encontrado para o e-mail desta conta.");return d.id}async function f(a){let{data:c,error:d}=await b.supabase.from("therapists").select("id").eq("profile_id",a).maybeSingle();if(d)throw Error(`N\xe3o foi poss\xedvel localizar o terapeuta: ${d.message}`);if(!c)throw Error("Nenhum terapeuta foi encontrado para esta conta.");return c.id}async function g(a){let{data:c,error:d}=await b.supabase.from("clients").select("id").eq("profile_id",a).maybeSingle();if(d)throw Error(`N\xe3o foi poss\xedvel localizar o cliente: ${d.message}`);if(!c)throw Error("Nenhum cliente foi encontrado para esta conta.");return c.id}async function h(a){let{data:c,error:e}=await b.supabase.from("appointments").select(`
        id,
        therapist_id,
        client_id,
        offer_id,
        client_name,
        client_email,
        client_phone,
        preferred_date,
        preferred_time,
        proposed_date,
        proposed_time,
        confirmed_date,
        confirmed_time,
        modality,
        message,
        therapist_response,
        price,
        status,
        appointment_date,
        created_at,
        updated_at,
        offer:offers (
          id,
          title,
          offer_type,
          offer_price,
          duration,
          service_type
        )
      `).eq("therapist_id",a).order("updated_at",{ascending:!1});if(e)throw Error(`N\xe3o foi poss\xedvel carregar os agendamentos: ${e.message}`);return d(c)}async function i(a){let{data:c,error:e}=await b.supabase.from("appointments").select(`
        id,
        therapist_id,
        client_id,
        offer_id,
        client_name,
        client_email,
        client_phone,
        preferred_date,
        preferred_time,
        proposed_date,
        proposed_time,
        confirmed_date,
        confirmed_time,
        modality,
        message,
        therapist_response,
        price,
        status,
        appointment_date,
        created_at,
        updated_at,
        offer:offers (
          id,
          title,
          offer_type,
          offer_price,
          duration,
          service_type
        )
      `).eq("client_id",a).order("updated_at",{ascending:!1});if(e)throw Error(`N\xe3o foi poss\xedvel carregar os atendimentos do cliente: ${e.message}`);return d(c)}async function j(a,c,d){let{error:e}=await b.supabase.from("appointments").update({status:"awaiting_payment",confirmed_date:c,confirmed_time:d,updated_at:new Date().toISOString()}).eq("id",a);if(e)throw Error(`N\xe3o foi poss\xedvel aceitar o agendamento: ${e.message}`)}async function k(a,c,d){let{error:e}=await b.supabase.from("appointments").update({status:"new_time_proposed",proposed_date:c,proposed_time:d,updated_at:new Date().toISOString()}).eq("id",a);if(e)throw Error(`N\xe3o foi poss\xedvel propor um novo hor\xe1rio: ${e.message}`)}async function l(a){let{error:c}=await b.supabase.from("appointments").update({status:"declined",updated_at:new Date().toISOString()}).eq("id",a);if(c)throw Error(`N\xe3o foi poss\xedvel recusar o agendamento: ${c.message}`)}a.s(["acceptAppointment",0,j,"declineAppointment",0,l,"getAppointmentsByClientId",0,i,"getAppointmentsByTherapistId",0,h,"getClientIdByProfileId",0,g,"getTherapistIdByEmail",0,e,"getTherapistIdByProfileId",0,f,"proposeNewAppointmentTime",0,k])},7287,a=>{"use strict";var b=a.i(87924),c=a.i(72131),d=a.i(50944),e=a.i(71897),f=a.i(78560);function g(a){return null==a?"Valor não informado":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:2,maximumFractionDigits:2}).format(a)}function h(a,b){return a instanceof Error&&a.message?a.message:b}function i(){return(0,b.jsx)("main",{className:"flex min-h-screen items-center justify-center bg-[#f7f8fc] px-6",children:(0,b.jsxs)("div",{className:"text-center",children:[(0,b.jsx)("div",{className:"mx-auto h-10 w-10 animate-spin rounded-full border-4 border-purple-200 border-t-purple-700"}),(0,b.jsx)("p",{className:"mt-4 text-sm font-semibold text-slate-600",children:"Carregando pagamento..."})]})})}function j(){let a=(0,d.useRouter)(),j=(0,d.useSearchParams)().get("appointmentId"),[k,l]=(0,c.useState)(null),[m,n]=(0,c.useState)(!0),[o,p]=(0,c.useState)(!1),[q,r]=(0,c.useState)(null),s=(0,c.useCallback)(async()=>{if(!j){r("O identificador do agendamento não foi informado."),n(!1);return}n(!0),r(null);try{let{data:{session:b},error:c}=await f.supabase.auth.getSession();if(c||!b?.user)return void a.replace("/login");let d=await (0,e.getClientIdByProfileId)(b.user.id),{data:g,error:h}=await f.supabase.from("appointments").select(`
              id,
              client_id,
              therapist_id,
              client_name,
              preferred_date,
              preferred_time,
              proposed_date,
              proposed_time,
              confirmed_date,
              confirmed_time,
              modality,
              price,
              status
            `).eq("id",j).eq("client_id",d).maybeSingle();if(h)throw h;if(!g){l(null),r("Este agendamento não foi localizado.");return}l(g)}catch(a){l(null),r(h(a,"Não foi possível carregar os dados do pagamento."))}finally{n(!1)}},[j,a]);async function t(){if(k){p(!0),r(null);try{let a=await fetch("/api/stripe/criar-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appointmentId:k.id})}),b=await a.json();if(!a.ok)throw Error(b?.error??"Não foi possível iniciar o pagamento.");if(!b?.url)throw Error("O Stripe não retornou a página de pagamento.");window.location.href=b.url}catch(a){r(h(a,"Não foi possível iniciar o pagamento.")),p(!1)}}}if((0,c.useEffect)(()=>{s()},[s]),m)return(0,b.jsx)(i,{});if(!k)return(0,b.jsx)("main",{className:"flex min-h-screen items-center justify-center bg-[#f7f8fc] px-6",children:(0,b.jsxs)("div",{className:"w-full max-w-md rounded-3xl border border-red-200 bg-white p-7 text-center shadow-sm",children:[(0,b.jsx)("h1",{className:"text-xl font-bold text-slate-950",children:"Pagamento não disponível"}),(0,b.jsx)("p",{className:"mt-3 text-sm leading-6 text-slate-600",children:q??"Não foi possível localizar este agendamento."}),(0,b.jsx)("button",{type:"button",onClick:()=>a.push("/painel-cliente"),className:"mt-6 min-h-11 rounded-xl bg-purple-700 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-purple-800",children:"Voltar ao painel"})]})});let u=k.confirmed_date??k.proposed_date??k.preferred_date,v=k.confirmed_time??k.proposed_time??k.preferred_time,w="awaiting_payment"===k.status;return(0,b.jsx)("main",{className:"min-h-screen bg-[#f7f8fc] px-4 py-8 sm:px-6 lg:py-12",children:(0,b.jsxs)("div",{className:"mx-auto w-full max-w-2xl",children:[(0,b.jsx)("button",{type:"button",onClick:()=>a.push("/painel-cliente"),className:"mb-6 text-sm font-semibold text-purple-700 transition hover:text-purple-900",children:"← Voltar ao painel"}),(0,b.jsxs)("section",{className:"overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm",children:[(0,b.jsxs)("div",{className:"bg-gradient-to-r from-purple-700 to-violet-600 px-6 py-7 text-white sm:px-8",children:[(0,b.jsx)("p",{className:"text-xs font-bold uppercase tracking-[0.18em] text-purple-100",children:"AuraMeets"}),(0,b.jsx)("h1",{className:"mt-2 text-2xl font-bold",children:"Pagamento da sessão"}),(0,b.jsx)("p",{className:"mt-2 text-sm leading-6 text-purple-100",children:"Confira os dados antes de continuar para o pagamento seguro."})]}),(0,b.jsxs)("div",{className:"space-y-6 p-6 sm:p-8",children:[(0,b.jsxs)("div",{className:"grid gap-4 sm:grid-cols-2",children:[(0,b.jsxs)("div",{className:"rounded-2xl bg-slate-50 p-4",children:[(0,b.jsx)("p",{className:"text-xs font-bold uppercase tracking-wide text-slate-500",children:"Data"}),(0,b.jsx)("p",{className:"mt-2 font-semibold text-slate-950",children:function(a){if(!a)return"Data não informada";let[b,c,d]=a.split("-");return b&&c&&d?`${d}/${c}/${b}`:a}(u)})]}),(0,b.jsxs)("div",{className:"rounded-2xl bg-slate-50 p-4",children:[(0,b.jsx)("p",{className:"text-xs font-bold uppercase tracking-wide text-slate-500",children:"Horário"}),(0,b.jsx)("p",{className:"mt-2 font-semibold text-slate-950",children:v?v.slice(0,5):"Horário não informado"})]}),(0,b.jsxs)("div",{className:"rounded-2xl bg-slate-50 p-4",children:[(0,b.jsx)("p",{className:"text-xs font-bold uppercase tracking-wide text-slate-500",children:"Modalidade"}),(0,b.jsx)("p",{className:"mt-2 font-semibold text-slate-950",children:k.modality??"Não informada"})]}),(0,b.jsxs)("div",{className:"rounded-2xl bg-purple-50 p-4",children:[(0,b.jsx)("p",{className:"text-xs font-bold uppercase tracking-wide text-purple-600",children:"Valor"}),(0,b.jsx)("p",{className:"mt-2 text-xl font-bold text-purple-800",children:g(k.price)})]})]}),q&&(0,b.jsx)("div",{role:"alert",className:"rounded-2xl border border-red-200 bg-red-50 px-5 py-4",children:(0,b.jsx)("p",{className:"text-sm font-medium text-red-700",children:q})}),!w&&(0,b.jsx)("div",{className:"rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4",children:(0,b.jsx)("p",{className:"text-sm font-medium text-amber-800",children:"Este agendamento não está aguardando pagamento."})}),(0,b.jsx)("button",{type:"button",onClick:()=>void t(),disabled:!w||o,className:"min-h-12 w-full rounded-xl bg-purple-700 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-purple-200 transition hover:bg-purple-800 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:shadow-none",children:o?"Abrindo pagamento...":`Pagar ${g(k.price)}`}),(0,b.jsx)("p",{className:"text-center text-xs leading-5 text-slate-500",children:"O pagamento será processado com segurança pelo Stripe."})]})]})]})})}a.s(["default",0,function(){return(0,b.jsx)(c.Suspense,{fallback:(0,b.jsx)(i,{}),children:(0,b.jsx)(j,{})})}])}];

//# sourceMappingURL=_1c6o23f._.js.map