var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/empresas/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__015p6dv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0alesp5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_17i19if._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w5bhzz.js")
R.c("server/chunks/ssr/[root-of-the-server]__1yfxjn4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nqskgw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_wvthf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_empresas_page_actions_11j1rfp.js")
R.m(70591)
module.exports=R.m(70591).exports
