var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/painel-cliente/avaliacao/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qb0qtr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0alesp5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_14fsnym.js")
R.c("server/chunks/ssr/node_modules_next_dist_17i19if._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1yfxjn4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nqskgw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_wvthf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_painel-cliente_layout_tsx_1q1r063._.js")
R.c("server/chunks/ssr/_next-internal_server_app_painel-cliente_avaliacao_page_actions_1gk0r7i.js")
R.m(42677)
module.exports=R.m(42677).exports
