// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/acolhimento" | "/acolhimento/perguntas" | "/admin" | "/admin/atendimentos" | "/admin/experiencias" | "/admin/falas-sistemicas" | "/admin/ofertas" | "/admin/pagamentos" | "/admin/terapeutas" | "/admin/terapeutas/[id]" | "/agenda" | "/agendar/[slug]" | "/cadastro" | "/cadastro-fundador" | "/dashboard" | "/dashboard-terapeuta" | "/dashboard-terapeuta/dados-profissionais" | "/dashboard-terapeuta/especialidades" | "/dashboard-terapeuta/experiencias" | "/dashboard-terapeuta/financeiro" | "/dashboard-terapeuta/perfil" | "/dashboard-terapeuta/servicos" | "/dashboard-terapeuta/servicos/novo" | "/dashboard-terapeuta/stripe" | "/dashboard/solicitacoes" | "/empresas" | "/esqueci-senha" | "/experiencias" | "/fala-sistemica" | "/jornada" | "/jornada/pergunta-1" | "/jornada/pergunta-10" | "/jornada/pergunta-11" | "/jornada/pergunta-12" | "/jornada/pergunta-2" | "/jornada/pergunta-3" | "/jornada/pergunta-4" | "/jornada/pergunta-5" | "/jornada/pergunta-6" | "/jornada/pergunta-7" | "/jornada/pergunta-8" | "/jornada/pergunta-9" | "/jornada/resultado" | "/login" | "/login-terapeuta" | "/ofertas/[slug]" | "/pagamento" | "/painel-cliente" | "/painel-cliente/atendimentos" | "/painel-cliente/avaliacao" | "/painel-cliente/terapeutas" | "/planos" | "/redefinir-senha" | "/seja-terapeuta" | "/seja-visitante" | "/terapeuta/[id]" | "/terapeuta/editar" | "/terapeutas" | "/terapeutas/[id]"
type AppRouteHandlerRoutes = "/api/cadastro-fundador" | "/api/sincronizar-terapeutas" | "/api/stripe/checkout" | "/api/stripe/connect" | "/api/stripe/diagnostico" | "/api/stripe/status" | "/api/terapeuta/perfil"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/painel-cliente"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/acolhimento": {}
  "/acolhimento/perguntas": {}
  "/admin": {}
  "/admin/atendimentos": {}
  "/admin/experiencias": {}
  "/admin/falas-sistemicas": {}
  "/admin/ofertas": {}
  "/admin/pagamentos": {}
  "/admin/terapeutas": {}
  "/admin/terapeutas/[id]": { "id": string; }
  "/agenda": {}
  "/agendar/[slug]": { "slug": string; }
  "/api/cadastro-fundador": {}
  "/api/sincronizar-terapeutas": {}
  "/api/stripe/checkout": {}
  "/api/stripe/connect": {}
  "/api/stripe/diagnostico": {}
  "/api/stripe/status": {}
  "/api/terapeuta/perfil": {}
  "/cadastro": {}
  "/cadastro-fundador": {}
  "/dashboard": {}
  "/dashboard-terapeuta": {}
  "/dashboard-terapeuta/dados-profissionais": {}
  "/dashboard-terapeuta/especialidades": {}
  "/dashboard-terapeuta/experiencias": {}
  "/dashboard-terapeuta/financeiro": {}
  "/dashboard-terapeuta/perfil": {}
  "/dashboard-terapeuta/servicos": {}
  "/dashboard-terapeuta/servicos/novo": {}
  "/dashboard-terapeuta/stripe": {}
  "/dashboard/solicitacoes": {}
  "/empresas": {}
  "/esqueci-senha": {}
  "/experiencias": {}
  "/fala-sistemica": {}
  "/jornada": {}
  "/jornada/pergunta-1": {}
  "/jornada/pergunta-10": {}
  "/jornada/pergunta-11": {}
  "/jornada/pergunta-12": {}
  "/jornada/pergunta-2": {}
  "/jornada/pergunta-3": {}
  "/jornada/pergunta-4": {}
  "/jornada/pergunta-5": {}
  "/jornada/pergunta-6": {}
  "/jornada/pergunta-7": {}
  "/jornada/pergunta-8": {}
  "/jornada/pergunta-9": {}
  "/jornada/resultado": {}
  "/login": {}
  "/login-terapeuta": {}
  "/ofertas/[slug]": { "slug": string; }
  "/pagamento": {}
  "/painel-cliente": {}
  "/painel-cliente/atendimentos": {}
  "/painel-cliente/avaliacao": {}
  "/painel-cliente/terapeutas": {}
  "/planos": {}
  "/redefinir-senha": {}
  "/seja-terapeuta": {}
  "/seja-visitante": {}
  "/terapeuta/[id]": { "id": string; }
  "/terapeuta/editar": {}
  "/terapeutas": {}
  "/terapeutas/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/painel-cliente": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
