// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/acolhimento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acolhimento">> = Specific
  const handler = {} as typeof import("../../app/acolhimento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/acolhimento/perguntas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acolhimento/perguntas">> = Specific
  const handler = {} as typeof import("../../app/acolhimento/perguntas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/atendimentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/atendimentos">> = Specific
  const handler = {} as typeof import("../../app/admin/atendimentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/experiencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/experiencias">> = Specific
  const handler = {} as typeof import("../../app/admin/experiencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/falas-sistemicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/falas-sistemicas">> = Specific
  const handler = {} as typeof import("../../app/admin/falas-sistemicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ofertas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ofertas">> = Specific
  const handler = {} as typeof import("../../app/admin/ofertas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/pagamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pagamentos">> = Specific
  const handler = {} as typeof import("../../app/admin/pagamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/terapeutas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/terapeutas/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/terapeutas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/terapeutas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/terapeutas">> = Specific
  const handler = {} as typeof import("../../app/admin/terapeutas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agenda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agenda">> = Specific
  const handler = {} as typeof import("../../app/agenda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agendar/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agendar/[slug]">> = Specific
  const handler = {} as typeof import("../../app/agendar/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cadastro-fundador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro-fundador">> = Specific
  const handler = {} as typeof import("../../app/cadastro-fundador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../app/cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/dados-profissionais/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/dados-profissionais">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/dados-profissionais/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/especialidades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/especialidades">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/especialidades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/experiencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/experiencias">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/experiencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/financeiro">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/perfil">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/servicos/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/servicos/novo">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/servicos/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/servicos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/servicos">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/servicos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard-terapeuta/stripe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-terapeuta/stripe">> = Specific
  const handler = {} as typeof import("../../app/dashboard-terapeuta/stripe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/solicitacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/solicitacoes">> = Specific
  const handler = {} as typeof import("../../app/dashboard/solicitacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empresas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empresas">> = Specific
  const handler = {} as typeof import("../../app/empresas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/esqueci-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esqueci-senha">> = Specific
  const handler = {} as typeof import("../../app/esqueci-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/experiencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experiencias">> = Specific
  const handler = {} as typeof import("../../app/experiencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fala-sistemica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fala-sistemica">> = Specific
  const handler = {} as typeof import("../../app/fala-sistemica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada">> = Specific
  const handler = {} as typeof import("../../app/jornada/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-1">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-10/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-10">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-10/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-11/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-11">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-11/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-12/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-12">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-12/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-2">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-3">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-4">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-5">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-6">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-7/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-7">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-7/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-8/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-8">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-8/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/pergunta-9/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/pergunta-9">> = Specific
  const handler = {} as typeof import("../../app/jornada/pergunta-9/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jornada/resultado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada/resultado">> = Specific
  const handler = {} as typeof import("../../app/jornada/resultado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login-terapeuta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login-terapeuta">> = Specific
  const handler = {} as typeof import("../../app/login-terapeuta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ofertas/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ofertas/[slug]">> = Specific
  const handler = {} as typeof import("../../app/ofertas/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pagamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pagamento">> = Specific
  const handler = {} as typeof import("../../app/pagamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/painel-cliente/atendimentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/painel-cliente/atendimentos">> = Specific
  const handler = {} as typeof import("../../app/painel-cliente/atendimentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/painel-cliente/avaliacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/painel-cliente/avaliacao">> = Specific
  const handler = {} as typeof import("../../app/painel-cliente/avaliacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/painel-cliente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/painel-cliente">> = Specific
  const handler = {} as typeof import("../../app/painel-cliente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/painel-cliente/terapeutas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/painel-cliente/terapeutas">> = Specific
  const handler = {} as typeof import("../../app/painel-cliente/terapeutas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planos">> = Specific
  const handler = {} as typeof import("../../app/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/redefinir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../app/redefinir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seja-terapeuta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seja-terapeuta">> = Specific
  const handler = {} as typeof import("../../app/seja-terapeuta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seja-visitante/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seja-visitante">> = Specific
  const handler = {} as typeof import("../../app/seja-visitante/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terapeuta/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terapeuta/[id]">> = Specific
  const handler = {} as typeof import("../../app/terapeuta/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terapeuta/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terapeuta/editar">> = Specific
  const handler = {} as typeof import("../../app/terapeuta/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terapeutas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terapeutas/[id]">> = Specific
  const handler = {} as typeof import("../../app/terapeutas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terapeutas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terapeutas">> = Specific
  const handler = {} as typeof import("../../app/terapeutas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cadastro-fundador/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cadastro-fundador">> = Specific
  const handler = {} as typeof import("../../app/api/cadastro-fundador/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sincronizar-terapeutas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sincronizar-terapeutas">> = Specific
  const handler = {} as typeof import("../../app/api/sincronizar-terapeutas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/connect">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/diagnostico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/diagnostico">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/diagnostico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/status">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/terapeuta/perfil/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terapeuta/perfil">> = Specific
  const handler = {} as typeof import("../../app/api/terapeuta/perfil/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/painel-cliente/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/painel-cliente">> = Specific
  const handler = {} as typeof import("../../app/painel-cliente/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
